# Day01--numpy的基础
numpy的核心


In [1]:
import numpy as np
ary = np.array([1, 2, 3, 4])
print(ary)

[1 2 3 4]


**ndarray数组的创建**

1. np.array(任何可被解释为数组的逻辑结构)

2. np.arange(起始值[0], 终止值, 步长[1])

3. np.zeros(数组元素个数, dtype='元素类型')

4. np.ones(数组元素个数, dtype='元素类型')

5. np.zeros_like(ary)

6. np.ones_like(ary)

In [4]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print('矩阵a：',a, a.shape)
# 起始值1, 终止值10, 步长1
b = np.arange(1, 10, 2)
print('矩阵b：',b)

# 创建5个元素全为0的数组
c = np.zeros(5, dtype='int32')
print('矩阵c：',c, c.dtype)

# 创建5个元素全为1的数组
d = np.ones(5, dtype='int32')
print('矩阵d：',d, d.dtype)
# 创建数组e与f, 结构与a相同, e中全0, f中全1
e = np.zeros_like(a)
f = np.ones_like(a)
print('矩阵e：',e)
print(f / 5)

矩阵a： [[1 2 3 4]
 [5 6 7 8]] (2, 4)
矩阵b： [1 3 5 7 9]
矩阵c： [0 0 0 0 0] int32
矩阵d： [1 1 1 1 1] int32
矩阵e： [[0 0 0 0]
 [0 0 0 0]]
[[0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2]]
