# 学习Xarray

https://xarray.pydata.org/en/stable/api.html

## 1.数组的读写操作

In [2]:
import numpy as np

import xarray as xr

import pandas as pd


filepath = "/home/liyuan3970/Data/data/meto_data/radar_typhoon_liqima/wenzhou_rada/out/Z_RADR_I_Z9577_20190809162900_O_DOR_SA_CAP.bin.bz2.nc"
f = xr.open_dataset(filepath,decode_times=False)
print(f)

<xarray.Dataset>
Dimensions:  (heigh: 46, lat: 251, lon: 251, time: 1)
Coordinates:
  * lat      (lat) float32 26.0 26.016 26.032 26.048 ... 29.968 29.984 30.0
  * lon      (lon) float32 118.0 118.02 118.04 118.06 ... 122.96 122.98 123.0
  * heigh    (heigh) float32 0.0 333.33334 666.6667 ... 14666.667 15000.0
  * time     (time) float64 9.969e+36
Data variables:
    ref      (time, heigh, lat, lon) float64 ...
    vt       (time, heigh, lat, lon) float64 ...
    u        (time, heigh, lat, lon) float64 ...
    v        (time, heigh, lat, lon) float64 ...
    w        (time, heigh, lat, lon) float64 ...
Attributes:
    title:    Z_RADR_I_Z9577_20190809162900_O_DOR_SA_CAP.bin.bz2


In [5]:
print(f.lat.data)

[26.    26.016 26.032 26.048 26.064 26.08  26.096 26.112 26.128 26.144
 26.16  26.176 26.192 26.208 26.224 26.24  26.256 26.272 26.288 26.304
 26.32  26.336 26.352 26.368 26.384 26.4   26.416 26.432 26.448 26.464
 26.48  26.496 26.512 26.528 26.544 26.56  26.576 26.592 26.608 26.624
 26.64  26.656 26.672 26.688 26.704 26.72  26.736 26.752 26.768 26.784
 26.8   26.816 26.832 26.848 26.864 26.88  26.896 26.912 26.928 26.944
 26.96  26.976 26.992 27.008 27.024 27.04  27.056 27.072 27.088 27.104
 27.12  27.136 27.152 27.168 27.184 27.2   27.216 27.232 27.248 27.264
 27.28  27.296 27.312 27.328 27.344 27.36  27.376 27.392 27.408 27.424
 27.44  27.456 27.472 27.488 27.504 27.52  27.536 27.552 27.568 27.584
 27.6   27.616 27.632 27.648 27.664 27.68  27.696 27.712 27.728 27.744
 27.76  27.776 27.792 27.808 27.824 27.84  27.856 27.872 27.888 27.904
 27.92  27.936 27.952 27.968 27.984 28.    28.016 28.032 28.048 28.064
 28.08  28.096 28.112 28.128 28.144 28.16  28.176 28.192 28.208 28.224
 28.24

In [7]:
print(f.u.data.shape)

(1, 46, 251, 251)


In [10]:
print(f.u.attrs)

{'units': 'm/s', 'standard_name': 'radar_wind_u'}


In [12]:
print(f.u.coords)

Coordinates:
  * lat      (lat) float32 26.0 26.016 26.032 26.048 ... 29.968 29.984 30.0
  * lon      (lon) float32 118.0 118.02 118.04 118.06 ... 122.96 122.98 123.0
  * heigh    (heigh) float32 0.0 333.33334 666.6667 ... 14666.667 15000.0
  * time     (time) float64 9.969e+36


In [21]:
a = f.u

a.isel(time=0,lat=26,lon=122)

<xarray.DataArray 'u' (heigh: 46)>
array([1.446904e+01, 1.500588e+01, 1.551285e+01, 1.610030e+01, 1.653405e+01,
       1.696164e+01, 1.708499e+01, 1.698755e+01, 1.710854e+01, 1.714755e+01,
       1.676631e+01, 1.651276e+01, 1.591033e+01, 1.591855e+01, 1.524266e+01,
       1.506271e+01, 1.434507e+01, 1.432197e+01, 1.318076e+01, 1.302686e+01,
       1.179425e+01, 1.216600e+01, 1.091692e+01, 9.969210e+36, 9.969210e+36,
       9.969210e+36, 9.969210e+36, 9.969210e+36, 9.969210e+36, 9.969210e+36,
       9.969210e+36, 9.969210e+36, 9.969210e+36, 9.969210e+36, 9.969210e+36,
       9.969210e+36, 9.969210e+36, 9.969210e+36, 9.969210e+36, 9.969210e+36,
       9.969210e+36, 9.969210e+36, 9.969210e+36, 9.969210e+36, 9.969210e+36,
       9.969210e+36])
Coordinates:
    lat      float32 26.416
    lon      float32 120.44
  * heigh    (heigh) float32 0.0 333.33334 666.6667 ... 14666.667 15000.0
    time     float64 9.969e+36
Attributes:
    units:          m/s
    standard_name:  radar_wind_u

### *根据的经纬度查询数据*

In [18]:
a = f.u


a.sel(lat=26.0,lon=118.02)

<xarray.DataArray 'u' (time: 1, heigh: 46)>
array([[9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
        9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
        9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
        9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
        9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
        9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
        9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
        9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
        9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
        9.96921e+36]])
Coordinates:
    lat      float32 26.0
    lon      float32 118.02
  * heigh    (heigh) float32 0.0 333.33334 666.6667 ... 14666.667 15000.0
  * time     (time) float64 9.969e+36
Attributes:
    units:          m/s
    standard_name:  radar_wind_u

## 2.pd和xr的相互转换

In [16]:
import numpy as np

import xarray as xr

import pandas as pd


filepath = "/home/liyuan3970/Data/data/meto_data/radar_typhoon_liqima/wenzhou_rada/out/Z_RADR_I_Z9577_20190809162900_O_DOR_SA_CAP.bin.bz2.nc"
f = xr.open_dataset(filepath,decode_times=False)

u= f.u[0,0,:,:]

pd_u = u.to_pandas()

pd_u

lon          118.000000    118.019997    118.040001    118.059998  \
lat                                                                 
26.000000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.016001  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.032000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.048000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.063999  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
...                 ...           ...           ...           ...   
29.936001  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
29.952000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
29.968000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
29.983999  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
30.000000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   

lon          118.080002    118.099998    118.120003    118.139999  \
lat                                                                 
26.000000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.016001  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.032000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.048000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.063999  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
...                 ...           ...           ...           ...   
29.936001  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
29.952000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
29.968000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
29.983999  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
30.000000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   

lon          118.160004    118.180000  ...    122.820000    122.839996  \
lat                                    ...                               
26.000000  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   
26.016001  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   
26.032000  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   
26.048000  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   
26.063999  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   
...                 ...           ...  ...           ...           ...   
29.936001  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   
29.952000  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   
29.968000  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   
29.983999  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   
30.000000  9.969210e+36  9.969210e+36  ...  9.969210e+36  9.969210e+36   

lon          122.860001    122.879997    122.900002    122.919998  \
lat                                                                 
26.000000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.016001  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.032000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.048000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
26.063999  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
...                 ...           ...           ...           ...   
29.936001  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
29.952000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
29.968000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
29.983999  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   
30.000000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36   

lon          122.940002    122.959999    122.980003    123.000000  
lat                                                                
26.000000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36  
26.016001  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36  
26.032000  9.969210e+36  9.969210e+36  9.969210e+36  9.969210e+36  
26.

In [17]:
xr_u = xr.DataArray(pd_u)
xr_u

<xarray.DataArray (lat: 251, lon: 251)>
array([[9.96920997e+36, 9.96920997e+36, 9.96920997e+36, ...,
        9.96920997e+36, 9.96920997e+36, 9.96920997e+36],
       [9.96920997e+36, 9.96920997e+36, 9.96920997e+36, ...,
        9.96920997e+36, 9.96920997e+36, 9.96920997e+36],
       [9.96920997e+36, 9.96920997e+36, 9.96920997e+36, ...,
        9.96920997e+36, 9.96920997e+36, 9.96920997e+36],
       ...,
       [9.96920997e+36, 9.96920997e+36, 9.96920997e+36, ...,
        9.96920997e+36, 9.96920997e+36, 9.96920997e+36],
       [9.96920997e+36, 9.96920997e+36, 9.96920997e+36, ...,
        9.96920997e+36, 9.96920997e+36, 9.96920997e+36],
       [9.96920997e+36, 9.96920997e+36, 9.96920997e+36, ...,
        9.96920997e+36, 9.96920997e+36, 9.96920997e+36]])
Coordinates:
  * lat      (lat) float64 26.0 26.02 26.03 26.05 ... 29.95 29.97 29.98 30.0
  * lon      (lon) float64 118.0 118.0 118.0 118.1 ... 122.9 123.0 123.0 123.0

# 经纬度数据的截取

In [ ]:
da = dv.sel(lat=slice(27,28), lon=slice(121, 122))